// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// calculate_cvs_log_scale
List calculate_cvs_log_scale(List fit);
RcppExport SEXP _EstimatingBiologicalVariation_calculate_cvs_log_scale(SEXP fitSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type fit(fitSEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_cvs_log_scale(fit));
    return rcpp_result_gen;
END_RCPP
}
// calculate_cvs_identity_scale
List calculate_cvs_identity_scale(List fit);
RcppExport SEXP _EstimatingBiologicalVariation_calculate_cvs_identity_scale(SEXP fitSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type fit(fitSEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_cvs_identity_scale(fit));
    return rcpp_result_gen;
END_RCPP
}
// apply_logt_scale_to_cv
NumericMatrix apply_logt_scale_to_cv(NumericMatrix mat, NumericVector df);
RcppExport SEXP _EstimatingBiologicalVariation_apply_logt_scale_to_cv(SEXP matSEXP, SEXP dfSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat(matSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type df(dfSEXP);
    rcpp_result_gen = Rcpp::wrap(apply_logt_scale_to_cv(mat, df));
    return rcpp_result_gen;
END_RCPP
}
// apply_exp_offset
NumericMatrix apply_exp_offset(NumericMatrix mat, NumericVector offset);
RcppExport SEXP _EstimatingBiologicalVariation_apply_exp_offset(SEXP matSEXP, SEXP offsetSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat(matSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type offset(offsetSEXP);
    rcpp_result_gen = Rcpp::wrap(apply_exp_offset(mat, offset));
    return rcpp_result_gen;
END_RCPP
}
// apply_add_offset
NumericMatrix apply_add_offset(NumericMatrix mat, NumericVector offset);
RcppExport SEXP _EstimatingBiologicalVariation_apply_add_offset(SEXP matSEXP, SEXP offsetSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat(matSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type offset(offsetSEXP);
    rcpp_result_gen = Rcpp::wrap(apply_add_offset(mat, offset));
    return rcpp_result_gen;
END_RCPP
}
// apply_t_scale_to_sd
NumericMatrix apply_t_scale_to_sd(NumericMatrix mat, NumericVector df);
RcppExport SEXP _EstimatingBiologicalVariation_apply_t_scale_to_sd(SEXP matSEXP, SEXP dfSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat(matSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type df(dfSEXP);
    rcpp_result_gen = Rcpp::wrap(apply_t_scale_to_sd(mat, df));
    return rcpp_result_gen;
END_RCPP
}
// process_stan_data_indexing
Rcpp::List process_stan_data_indexing(Rcpp::CharacterVector SubjectID_orig_R, Rcpp::IntegerVector SampleID_orig_R, Rcpp::NumericVector y_R);
RcppExport SEXP _EstimatingBiologicalVariation_process_stan_data_indexing(SEXP SubjectID_orig_RSEXP, SEXP SampleID_orig_RSEXP, SEXP y_RSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type SubjectID_orig_R(SubjectID_orig_RSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type SampleID_orig_R(SampleID_orig_RSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y_R(y_RSEXP);
    rcpp_result_gen = Rcpp::wrap(process_stan_data_indexing(SubjectID_orig_R, SampleID_orig_R, y_R));
    return rcpp_result_gen;
END_RCPP
}
// process_stan_data_priors
List process_stan_data_priors(double beta, double cvi, double cva, double cvg, double dfi, double dfa, double hbhr, NumericVector strength, bool log_transformed);
RcppExport SEXP _EstimatingBiologicalVariation_process_stan_data_priors(SEXP betaSEXP, SEXP cviSEXP, SEXP cvaSEXP, SEXP cvgSEXP, SEXP dfiSEXP, SEXP dfaSEXP, SEXP hbhrSEXP, SEXP strengthSEXP, SEXP log_transformedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type cvi(cviSEXP);
    Rcpp::traits::input_parameter< double >::type cva(cvaSEXP);
    Rcpp::traits::input_parameter< double >::type cvg(cvgSEXP);
    Rcpp::traits::input_parameter< double >::type dfi(dfiSEXP);
    Rcpp::traits::input_parameter< double >::type dfa(dfaSEXP);
    Rcpp::traits::input_parameter< double >::type hbhr(hbhrSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type strength(strengthSEXP);
    Rcpp::traits::input_parameter< bool >::type log_transformed(log_transformedSEXP);
    rcpp_result_gen = Rcpp::wrap(process_stan_data_priors(beta, cvi, cva, cvg, dfi, dfa, hbhr, strength, log_transformed));
    return rcpp_result_gen;
END_RCPP
}
// bv_anova
Rcpp::List bv_anova(Rcpp::List data, bool cv_anova);
RcppExport SEXP _EstimatingBiologicalVariation_bv_anova(SEXP dataSEXP, SEXP cv_anovaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type data(dataSEXP);
    Rcpp::traits::input_parameter< bool >::type cv_anova(cv_anovaSEXP);
    rcpp_result_gen = Rcpp::wrap(bv_anova(data, cv_anova));
    return rcpp_result_gen;
END_RCPP
}
// variance_components
Rcpp::List variance_components(List data, std::string output_type, double mult, double level, bool cv_anova);
RcppExport SEXP _EstimatingBiologicalVariation_variance_components(SEXP dataSEXP, SEXP output_typeSEXP, SEXP multSEXP, SEXP levelSEXP, SEXP cv_anovaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type data(dataSEXP);
    Rcpp::traits::input_parameter< std::string >::type output_type(output_typeSEXP);
    Rcpp::traits::input_parameter< double >::type mult(multSEXP);
    Rcpp::traits::input_parameter< double >::type level(levelSEXP);
    Rcpp::traits::input_parameter< bool >::type cv_anova(cv_anovaSEXP);
    rcpp_result_gen = Rcpp::wrap(variance_components(data, output_type, mult, level, cv_anova));
    return rcpp_result_gen;
END_RCPP
}
// bv_anova_bootstrap_ci
List bv_anova_bootstrap_ci(List data_orig, int B, double level, std::string output_type_for_point_est, double mult);
RcppExport SEXP _EstimatingBiologicalVariation_bv_anova_bootstrap_ci(SEXP data_origSEXP, SEXP BSEXP, SEXP levelSEXP, SEXP output_type_for_point_estSEXP, SEXP multSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type data_orig(data_origSEXP);
    Rcpp::traits::input_parameter< int >::type B(BSEXP);
    Rcpp::traits::input_parameter< double >::type level(levelSEXP);
    Rcpp::traits::input_parameter< std::string >::type output_type_for_point_est(output_type_for_point_estSEXP);
    Rcpp::traits::input_parameter< double >::type mult(multSEXP);
    rcpp_result_gen = Rcpp::wrap(bv_anova_bootstrap_ci(data_orig, B, level, output_type_for_point_est, mult));
    return rcpp_result_gen;
END_RCPP
}
